name: Example Daft Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-example-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run example script file
        id: run_script
        uses: ./
        with:
          script_file: 'example_script.py'
          daft_version: 'latest'
      - name: Show job summary (formatted as a code block)
        run: |
          echo -e "\`\`\`\n${{ steps.run_script.outputs.result }}\n\`\`\`" >> $GITHUB_STEP_SUMMARY
